export const PetDetailsEntries = [
  {
    isTextInput: true,
    name: "firstText",
    label: "Banner ",
    breakpoint: 3,
    type: "text",
    customClass: "textBox",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
  },
  {
    isFileUploader: true,
    name: "fileUploader",
    label: "Upload Image",
    // pattern: /^.*\.(jpg|jpeg|gif|JPG|png|PNG)$/,
    pattern: /\.(jpeg|png|gif|bmp)$/i,
    breakpoint: 3,
    customClass: "uploadImageContainer",
    validation: { required: true },
    error_message: "Upload Image",
  },
  {
    isRadioAction: true,
    name: "gender",
    label: "Status",
    breakpoint: 3,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    defaultValue: "Male",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isEmptySpace: true,
    breakpoint: 1,
    name: "space",
  },
  {
    isSubmitButton: true,
    name: "submit_button",
    buttonTitle: "Submit",
    breakpoint: 1,
    customClass: "sourceButton",
  },
  {
    isCancelButton: true,
    name: "submit_button",
    buttonTitle: "Cancel",
    breakpoint: 1,
    customClass: "sourceButton",
  },
];

