export const AstrologerEntries = [
  {
    isRadioAction: true,
    name: 'user_type',
    breakpoint: 3,
    radioButtonData: [{ name: 'Astrologer' }, { name: 'Purohit' }],
    customClass: 'user_types',
    validation: { required: true },
  },
];
export const PreferenceEntries = [
  {
    isTextInput: true,
    name: 'Review',
    label: 'Review',
    // pattern: /^[A-Za-z][A-Za-z0-9_]{7,29}$/,
    breakpoint: 6,
    multiline: true,
    rows: 2,
    customClass: 'textBox',
    requiredField: true,
    validation: { required: true },
  },
  {
    isDropdown: true,
    name: 'status',
    breakpoint: 3,
    label: 'Status',
    // placeholder: 'Ads Place',
    disabled: false,
    DropdownData: [
      {
        id: 1,
        value: 'Proceed',
      },
      {
        id: 2,
        value: 'Rejected',
      },
      {
        id: 3,
        value: 'Hold',
      },
    ],
    validation: { required: true },
  },
  {
    isSubmitButton: true,
    name: 'submit_button',
    buttonTitle: 'Submit',
    breakpoint: 1.5,
    customClass: 'sourceButton',
  },
  {
    isCancelButton: true,
    name: 'submit_button',
    buttonTitle: 'Cancel',
    breakpoint: 1.5,
    customClass: 'sourceButton',
  },
];

export const AstroProfileEntries = [
  {
    isCustomTypography: true,
    name: 'basic_details',
    text: 'Basic Details',
    breakpoint: 12,
    customClass: 'login_header',
  },
  {
    isRadioAction: true,
    name: 'user_type',
    label: 'User Type',
    breakpoint: 3,
    radioButtonData: [{ name: 'Astrologer' }, { name: 'Purohit' }, { name: 'Both' }],
    customClass: 'user_types',
    validation: { required: true },
    error_message: 'User Type',
  },
  {
    isTextInput: true,
    name: 'name',
    label: 'Astrologer / Purohit Name',
    breakpoint: 3,
    // pattern: /^[A-Za-z][A-Za-z0-9_]{7,29}$/,
    validation_error_message: 'Name is in Invalid format',
    type: 'text',
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    IsPattern: true,
    customClass: 'textBox',
    error_message: 'Name',
  },
  {
    isTextInput: true,
    name: 'display_name',
    label: 'Display Name',
    breakpoint: 3,
    validation_error_message: 'Name is in Invalid format',
    type: 'text',
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    IsPattern: true,
    customClass: 'textBox',
    error_message: 'Display Name',
  },
  {
    isFileUploader: true,
    name: 'image',
    breakpoint: 3,
    customClass: 'circleUpload',
    label: 'Profile',
    regForm: true,
    pattern: /\.(jpeg|png|gif|bmp)$/i,
    validation: { required: true },
    requiredField: true,
    error_message: 'Image',
    className: 'logoText',
  },

  {
    isBirthdayPicker: true,
    name: 'dob',
    date: true,
    label: 'Date of Birth',
    placeholder: 'DD-MM-YYYY',
    pattern: /^\d{2}-[a-zA-Z]{3}-\d{4}$/,
    breakpoint: 3,
    validation_error_message: 'Date of Birth is in Invalid format',
    validation: { required: true },
    requiredField: true,
    maxDate: '11/02/2004',
    error_message: 'Date of Birth',
  },

  {
    isTextInput: true,
    name: 'mobile_number',
    label: 'Mobile Number',
    breakpoint: 3,
    type: 'number',
    pattern: /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/,
    validation: { required: true },
    validation_error_message: 'Mobile number must be 10 digits.',
    requiredField: true,
    error_message: 'Mobile Number',
  },
  {
    isTextInput: true,
    name: 'email',
    label: 'Email',
    breakpoint: 3,
    pattern: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i,
    validation: { required: true },
    requiredField: true,
    customClass: 'linkBox',
    error_message: 'Email',
    validation_error_message: 'This email address is not valid or supported ',
  },
  {
    isEmptySpace: true,
    breakpoint: 3,
    name: 'space',
  },
  {
    isTextInput: true,
    name: 'experience_year',
    error_message: 'Experience',
    label: 'Experience (In Years)',
    placeholder: 'Eg:35',
    type: 'number',
    // pattern: /\b([0-9]|[1-6][0-9])\b/,
    // pattern: /\b([0-9]|[1-9][0-9])\b/,
    pattern: /^(?:[1-9]|[1-4][0-9]|50)$/,
    breakpoint: 3,
    validation: { required: true },
    requiredField: true,
    validation_error_message: 'Valid upto 50 Years only!',
    // IsPattern: true,
  },

  {
    isTextInput: true,
    name: 'description',
    label: 'Description',
    breakpoint: 6,
    pattern: /^.{5,150}$/,
    // pattern: /\b([1-9]|[1-9][0-9]|100)\b/,
    validation: { required: true },
    requiredField: true,
    error_message: 'Description',
    customClass: 'descriptionBox',
    validation_error_message: 'Valid upto 150 characters only !',
  },
  {
    isEmptySpace: true,
    breakpoint: 3,
    name: 'space',
  },
  {
    isCustomTypography: true,
    name: 'preferences',
    text: 'Preferences',
    breakpoint: 12,
    customClass: 'login_header',
  },

  {
    isMultipleSelectChip: true,
    name: 'primary_skills',
    breakpoint: 3,
    label: 'Primary Skills',
    labelText: 'Primary Skills',
    dropPlaceholder: 'Primary Skills',
    disabled: true,
    DropdownData: [
      {
        id: 1,
        value: 'Cartomancy',
      },
      {
        id: 2,
        value: 'Face Reading',
      },
      {
        id: 3,
        value: 'Lal Kitab',
      },
      {
        id: 4,
        value: 'Life Coach',
      },
      {
        id: 5,
        value: 'Loshu Grid',
      },
      {
        id: 6,
        value: 'Motivational Coach',
      },
      {
        id: 7,
        value: 'Nadi Astrology',
      },
      {
        id: 8,
        value: 'Numerology',
      },
      {
        id: 9,
        value: 'Palmistry',
      },
      {
        id: 10,
        value: 'Prashana',
      },
      {
        id: 11,
        value: 'Psychic',
      },
      {
        id: 12,
        value: 'Psychologist',
      },
      {
        id: 13,
        value: 'Tarot Reading',
      },
      {
        id: 14,
        value: 'Vastu',
      },
      {
        id: 15,
        value: 'Vedic Astrology',
      },
      {
        id: 16,
        value: 'Western',
      },
    ],
    validation: { required: true },
    error_message: 'Primary Skills',
  },
  {
    isMultipleSelectChip: true,
    name: 'language',
    breakpoint: 3,
    label: 'Languages',
    labelText: 'Languages',
    dropPlaceholder: 'Languages',
    disabled: true,
    DropdownData: [
      {
        id: 1,
        value: 'Assamese',
      },
      {
        id: 2,
        value: 'Bengali',
      },
      {
        id: 3,
        value: 'Bhojpuri',
      },
      {
        id: 4,
        value: 'Chinese',
      },
      {
        id: 5,
        value: 'Dogri',
      },
      {
        id: 6,
        value: 'English',
      },
      {
        id: 7,
        value: 'French',
      },
      {
        id: 8,
        value: 'Gujarati',
      },
      {
        id: 9,
        value: 'Haryanvi',
      },
      {
        id: 10,
        value: 'Hindi',
      },
      {
        id: 11,
        value: 'Kannada',
      },
      {
        id: 12,
        value: 'Kashmiri',
      },
      {
        id: 13,
        value: 'Konkani',
      },
      {
        id: 14,
        value: 'Kumaoni',
      },
      {
        id: 15,
        value: 'maithili',
      },
      {
        id: 16,
        value: 'Malayalam',
      },
      {
        id: 17,
        value: 'Manipuri',
      },
      {
        id: 18,
        value: 'Marathi',
      },
      {
        id: 19,
        value: 'Nepali',
      },
      {
        id: 20,
        value: 'Odia',
      },
      {
        id: 21,
        value: 'Portuguese',
      },
      {
        id: 22,
        value: 'Punjabi',
      },
      {
        id: 23,
        value: 'Rajasthani',
      },
      {
        id: 24,
        value: 'Sanskrit',
      },
      {
        id: 25,
        value: 'Santali',
      },
      {
        id: 26,
        value: 'Sindhi',
      },
      {
        id: 27,
        value: 'Sinhalese',
      },
      {
        id: 28,
        value: 'Tamil',
      },
      {
        id: 29,
        value: 'Telugu',
      },
      {
        id: 30,
        value: 'Tulu',
      },
      {
        id: 31,
        value: 'Udia',
      },
    ],
    validation: { required: true },
    error_message: 'Languages',
  },
  {
    isMultipleSelectChip: true,
    name: 'preferred_mode_of_contact',
    breakpoint: 3,
    label: 'Preferred mode of contact',
    labelText: 'Preferred mode of contact',
    dropPlaceholder: 'Phone/WhatsApp call',
    disabled: true,
    DropdownData: [
      {
        value: 'Email',

        id: 1,
      },
      {
        value: 'Phone/WhatsApp call',

        id: 2,
      },
      {
        value: 'WhatsApp',
        id: 3,
      },
      {
        value: 'video',
        id: 4,
      },
    ],
    validation: { required: true },
    error_message: 'Preferred mode of contact',
  },
  {
    isRadioAction: true,
    name: 'astrologer_type',
    label: 'Astrologer Type',
    breakpoint: 3,
    radioButtonData: [{ name: 'Premium' }, { name: 'Standard' }],
    validation: { required: true },
    error_message: 'Astrologer Type',
  },
  // {
  //   isRadioAction: true,
  //   name: 'partTime_Work',
  //   label: 'Are You Working on any other Online Platform?',
  //   breakpoint: 3,
  //   radioButtonData: [{ name: 'Yes' }, { name: 'No' }],
  //   validation: { required: true },
  // },
  {
    isRadioAction: true,
    name: 'astrologer_verify',
    label: 'Astrologer Verified',
    breakpoint: 3,
    radioButtonData: [{ name: 'Yes' }, { name: 'No' }],
    validation: { required: true },
    error_message: 'Astrologer Verified',
  },

  {
    isCustomTypography: true,
    name: 'address_name',
    text: 'Book Slot',
    breakpoint: 12,
    customClass: 'login_header',
  },
  {
    bookSlotTable: true,
    name: 'audioCall',
    subHeader: true,
    slotLable: 'Call',
    type: 'audioCall',
  },
  {
    bookSlotTable: true,
    name: 'video',
    subHeader: true,
    slotLable: 'Video',
    type: 'video',
  },
  {
    bookSlotTable: true,
    name: 'chat',
    subHeader: true,
    slotLable: 'Chat',
    type: 'chat',
  },
  {
    bookSlotTable: true,
    name: 'report',
    subHeader: true,
    slotLable: 'Report',
    type: 'report',
  },

  {
    isEmptySpace: true,
    breakpoint: 3,
    name: 'space',
  },

  {
    isEmptySpace: true,
    breakpoint: 3,
    name: 'space',
  },

  {
    isCustomTypography: true,
    name: 'address_name',
    text: 'Address',
    breakpoint: 12,
    customClass: 'login_header',
  },

  {
    isEmptySpace: true,
    breakpoint: 12,
    name: 'space',
  },
  // {
  //   isTextInput: true,
  //   name: 'country',
  //   label: 'Country',
  //   breakpoint: 3,
  //   // pattern: /^[A-Za-z][A-Za-z0-9_]{7,29}$/,
  //   validation_error_message: 'country is in Invalid format',
  //   type: 'text',
  //   pattern: /^[a-zA-Z ]*$/,
  //   validation: { required: true },
  //   requiredField: true,
  //   IsPattern: true,
  //   error_message: 'Country',
  // },
  // {
  //   isCountry : true,
  //   name: 'country',
  //   label: 'Country',
  //   breakpoint: 3,
  //       validation: { required: true },
  //   requiredField: true,

  // },
  {
    isDropdown: true,
    name: 'country',
    // label: 'Country',
    breakpoint: 3,
    labelText: 'Country',
    disabled: true,
    DropdownData: [
      {
        id: 1,
        value: 'India',
      },
      // {
      //   id: 2,
      //   value: 'Malaysia',
      // },
      // {
      //   id: 3,
      //   value: 'Singapore',
      // },
    ],
    validation: { required: true },
    error_message: 'Country',
  },

  // {
  //   isTextInput: true,
  //   name: 'state',
  //   label: 'State',
  //   breakpoint: 3,
  //   // pattern: /^[A-Za-z][A-Za-z0-9_]{7,29}$/,
  //   validation_error_message: 'State is in Invalid format',
  //   type: 'text',
  //   pattern: /^[a-zA-Z ]*$/,
  //   validation: { required: true },
  //   requiredField: true,
  //   IsPattern: true,
  //   error_message: 'State',
  // },
  {
    isDropdown: true,
    name: 'birth_state',
    labelText: 'State',
    breakpoint: 3,
    placeholder: 'Birth State',
    disabled: true,
    error_message: 'State is required',
    DropdownData: [
      {
        id: 1,
        value: 'Andhra Pradesh',
      },
      {
        id: 2,
        value: 'Arunachal Pradesh',
      },
      {
        id: 3,
        value: 'Assam',
      },
      {
        id: 4,
        value: 'Bihar',
      },
      {
        id: 5,
        value: 'Chhattisgarh',
      },
      {
        id: 6,
        value: 'Goa',
      },
      {
        id: 7,
        value: 'Gujarat',
      },
      {
        id: 8,
        value: 'Haryana',
      },
      {
        id: 9,
        value: 'Himachal Pradesh',
      },
      {
        id: 10,
        value: 'Jharkhand',
      },
      {
        id: 11,
        value: 'Karnataka',
      },
      {
        id: 12,
        value: 'Kerala',
      },
      {
        id: 13,
        value: 'Madhya Pradesh',
      },
      {
        id: 14,
        value: 'Maharashtra',
      },
      {
        id: 15,
        value: 'Manipur',
      },
      {
        id: 16,
        value: 'Meghalaya',
      },
      {
        id: 17,
        value: 'Mizoram',
      },
      {
        id: 18,
        value: 'Nagaland',
      },
      {
        id: 19,
        value: 'Odisha',
      },
      {
        id: 20,
        value: 'Punjab',
      },
      {
        id: 21,
        value: 'Rajasthan',
      },
      {
        id: 22,
        value: 'Sikkim',
      },
      {
        id: 23,
        value: 'Tamil Nadu',
      },
      {
        id: 24,
        value: 'Telangana',
      },
      {
        id: 25,
        value: 'Tripura',
      },
      {
        id: 26,
        value: 'Uttarakhand',
      },
      {
        id: 27,
        value: 'Uttar Pradesh',
      },
      {
        id: 28,
        value: 'West Bengal',
      },
    ],
    validation: { required: true },
    requiredField: true,
    className: 'state_dropdown',
  },
  {
    isTextInput: true,
    name: 'city',
    label: 'City',
    breakpoint: 3,
    // pattern: /^[A-Za-z][A-Za-z0-9_]{7,29}$/,
    validation_error_message: 'City is in Invalid format',
    type: 'text',
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    IsPattern: true,
    customClass: 'textBox',
    error_message: 'City',
  },
  // {
  //   isDropdown: true,
  //   name: 'city',
  //   // label: 'Country',
  //   breakpoint: 3,
  //   labelText: 'City',
  //   disabled: true,
  //   DropdownData: [
  //     {
  //       id: 1,
  //       value: 'Ambala',
  //     },
  //     {
  //       id: 2,
  //       value: 'Amaravati',
  //     },
  //     {
  //       id: 3,
  //       value: 'Bangalore',
  //     },
  //     {
  //       id: 4,
  //       value: 'Cochin',
  //     },
  //     {
  //       id: 5,
  //       value: 'Chennai',
  //     },
  //     {
  //       id: 6,
  //       value: 'Manali',
  //     },
  //     {
  //       id: 7,
  //       value: 'Haridwar',
  //     },
  //   ],
  //   validation: { required: true },
  //   error_message: 'Country',
  // },
  {
    isTextInput: true,
    name: 'post_code',
    label: 'Post Code',
    pattern: /(^\d{6}$)|(^\d{6}-\d{6}$)/,
    breakpoint: 3,
    type: 'number',
    validation: { required: true },
    error_message: 'Post Code',
    validation_error_message: 'Post Code is in Invalid format',
  },
  {
    isTextInput: true,
    name: 'address',
    label: 'Address Details',
    // pattern: /^[a-zA-Z]*$/,
    breakpoint: 3,
    customClass: 'textBox',
    validation: { required: true },
    error_message: 'Address Details',
  },
  {
    isTextInput: true,
    name: 'alternate_number',
    label: 'Alternate Mobile Number',
    pattern: /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/,
    breakpoint: 3,
    type: 'number',
    // validation: { required: true },
    error_message: 'Alternate Mobile Number',
    validation_error_message: 'Mobile Number is in Invalid format',
    // requiredField: true,
  },
  {
    isDropdown: true,
    name: 'status',
    // label: 'Status',
    breakpoint: 3,
    labelText: 'Status',
    // disabled: false,
    DropdownData: [
      {
        id: 1,
        value: 'Active',
      },
      {
        id: 2,
        value: 'Inactive',
      },
      {
        id: 3,
        value: 'Pending',
      },
    ],
    validation: { required: true },
    error_message: 'Status',
  },

  {
    isSubmitButton: true,
    name: 'submit_button',
    label: 'SUBMIT',
    breakpoint: 1,
    buttonTitle: 'SUBMIT',
  },
  {
    isCancelButton: true,
    name: 'cancel_button',
    label: 'CANCEL',
    breakpoint: 1,
    buttonTitle: 'CANCEL',
  },
];
export const AstroLoginDefaultValues = {
  user_type: '',
  name: '',
  display_name: '',
  dob: '',
  mobile_number: '',
  image: '',
  email: '',
  experience_year: '',
  description: '',
  primary_skills: [],
  language: [],
  preferred_mode_of_contact: [],
  online_platform: false,
  astrologer_verify: 1,
  country: '',
  state: '',
  city: '',
  post_code: '',
  address: '',
  status: 0,
};
