export const PHBAYPetBoardingSpaceEntries = [
  // {
  //   isTextInput: true,
  //   name: "type_of_boarding",
  //   label: "Type of Boarding",
  //   value: "state",
  //   placeholder: "Individual House",
  //   breakpoint: 6,
  //   validation: { required: true },
  //   pattern: /^[a-zA-Z ]*$/,
  //   requiredField: true,

  //   error_message: "First Text",
  //   validation_error_message: "Text is in Invalid format",
  // },

  {
    isDropdown: true,
    name: "type_of_boarding",
    labelText: "Type of Boarding",
    placeholder: "Individual House",
    DropdownData: [
      {
        id: 1,
        value: "Kennel",
      },
      {
        id: 2,
        value: "Professional Boarding Space",
      },
      {
        id: 3,
        value: "Hospital",
      },
      {
        id: 4,
        value: "Pet Resort",
      },
      {
        id: 5,
        value: "Apartment",
      },
      {
        id: 6,
        value: "Individual House",
      },
      {
        id: 7,
        value: "Villa",
      },
    ],
    breakpoint: 6,
    disabled: true,
    customClass: "TypeOfBoarding",
    validation: { required: true },
  },
  // {
  //   isCustomTypography: true,
  //   name: 'basic_details',
  //   text: 'Type of Boarding',
  //   breakpoint: 12,
  //   customClass: 'login_header',
  // },
  // {
  //   isDropdown: true,
  //   name: "firstText",
  //   label: "Professional Status",
  //   placeholder: "Select Profession",
  //   DropdownData: [
  //     {
  //       id: 1,
  //       value: "Student",
  //     },
  //     {
  //       id: 2,
  //       value: "Housewife",
  //     },
  //     {
  //       id: 3,
  //       value: "Professional boarder",
  //     },
  //     {
  //       id: 4,
  //       value: "Working Professional",
  //     },
  //   ],
  //   breakpoint: 6,
  //   disabled: true,
  //   validation: { required: true },
  // },
  {
    isMultipleSelectChip: true,
    name: "category_of_pet_boarded",
    breakpoint: 6,
    label: "Category of Pet Boarded",
    labelText: "Category of Pet Boarded ",
    dropPlaceholder: "Category of Pet Boarded",
    disabled: true,
    DropdownData: [
      // {
      //   id: 1,
      //   value: "Cat",
      // },
      // {
      //   id: 2,
      //   value: "Dog",
      // },
      // {
      //   id: 3,
      //   value: "Birds",
      // },
    ],
    validation: { required: true },
    error_message: "Category of Pet Boarded",
  },
  //   {
  //     isTextInput: true,
  //     name: "secondText",
  //     label: "Category of Pet Boarded",
  //     placeholder: "Cat",
  //     breakpoint: 6,
  //     validation: { required: true },
  //     pattern: /^[a-zA-Z ]*$/,
  //     requiredField: true,
  //
  //     error_message: "First Text",
  //     validation_error_message: "Text is in Invalid format",
  //   },
  {
    isTextInput: true,
    name: "no_of_pets",
    type: "number",
    label: "Boarding Capacity (No. of Pets)",
    placeholder: "Enter Number",
    breakpoint: 6,
    validation: { required: true },
    // pattern: /^[a-zA-Z ]*$/,
    requiredField: true,

    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "total_sq_feet_of_the_space",
    type: "number",
    label: "Total Area of the Space (in sq.ft)",
    placeholder: "Enter Number",
    breakpoint: 6,
    validation: { required: true },
    // pattern: /^[a-zA-Z ]*$/,
    requiredField: true,

    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "price_for_per_day_boarding",
    type: "number",
    label: "Price for Per Day Boarding (24 Hours) ",
    placeholder: "Enter Price",
    breakpoint: 6,
    validation: { required: true },
    // pattern: /^[a-zA-Z ]*$/,
    requiredField: true,

    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "price_for_day_care",
    type: "number",
    label: "Price for Day Care (8 Hours)",
    placeholder: "Enter Price",
    breakpoint: 6,
    validation: { required: true },
    // pattern: /^[a-zA-Z ]*$/,
    requiredField: true,

    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "no_of_bedrooms",
    type: "number",
    label: "No of Bed Rooms",
    placeholder: "Enter Number",
    breakpoint: 6,
    validation: { required: true },
    // pattern: /^[a-zA-Z ]*$/,
    requiredField: true,

    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "how_many_pets_can_you_host_at_max",
    type: "number",
    label: "How many pets can you host at max?",
    placeholder: "Enter a Number",
    breakpoint: 6,
    validation: { required: true },
    // pattern: /^[a-zA-Z ]*$/,
    requiredField: true,

    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  // {
  //   isCustomTypography: true,
  //   // name: 'basic_details',
  //   text: "Add Photos",
  //   breakpoint: 10,
  //   // customClass: "login_header",
  // },
  {
    isFileUploader: true,
    name: "photos",
    label: "Choose minimum 4 images (Ctrl + Select Image) ",
    placeholder: "Choose minimum 4 images",
    breakpoint: 12,
    pattern: /^.{0,499999}$/i,
    customClass: "uploadImageContainer",
    validation: { required: true },
    error_message: "Upload Image",
  },
];
export const DefaultPHBAYPetBoardingSpaceValues = {
  type_of_boarding: "",
  category_of_pet_boarded: "",
  no_of_pets: "",
  total_sq_feet_of_the_space: "",
  price_for_per_day_boarding: "",
  price_for_day_care: "",
  no_of_bedrooms: "",
  how_many_pets_can_you_host_at_max: "",
  photos: "",
};
