export const PHBAboutYouEntries = [
  {
    isDropdown: true,
    name: "professional_status",
    label: "Professional Status",
    labelText: "Professional Status",
    placeholder: "Select Profession",
    DropdownData: [
      {
        id: 1,
        value: "Student",
      },
      {
        id: 2,
        value: "Housewife",
      },
      {
        id: 3,
        value: "Professional boarder",
      },
      {
        id: 4,
        value: "Working Professional",
      },
    ],
    breakpoint: 6,
    disabled: true,
    validation: { required: true },
  },
  {
    isDropdown: true,
    name: "years_of_experience",
    label: "Years Of Experience",
    labelText: "Years Of Experience",
    placeholder: "Select Years",
    DropdownData: [
      {
        id: 2,
        value: 1,
      },
      {
        id: 3,
        value: 2,
      },
      {
        id: 4,
        value: 3,
      },
      {
        id: 5,
        value: 4,
      },
      {
        id: 6,
        value: 5,
      },
      {
        id: 7,
        value: 6,
      },
      {
        id: 8,
        value: 7,
      },
      {
        id: 9,
        value: 8,
      },
      {
        id: 10,
        value: 9,
      },
      {
        id: 1,
        value: 10,
      },
    ],
    breakpoint: 6,
    disabled: true,
    validation: { required: true },
  },
  {
    isTextInput: true,
    name: "tell_us_somthing_about_you",
    label: "Tell us Something about you and your passion towards pet",
    placeholder: "",
    breakpoint: 12,
    multiline: true,
    rows: 4,
    validation: { required: true },
    // pattern: /^[a-zA-Z ]*$/,
    requiredField: true,

    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "tell_us_about_the_type_of_pet_and_your_experience",
    label:
      "Tell us about the type of pet you have and your experience in boarding",
    placeholder: "",
    breakpoint: 12,
    multiline: true,
    rows: 4,
    validation: { required: true },
    // pattern: /^[a-zA-Z ]*$/,
    requiredField: true,

    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  //   {
  //     isTextInput: true,
  //     name: "tell_us_about_the_type_of_pet_you_have_and_your_experience_two",
  //     label:
  //       "Tell us about the type of pet you have and your experience in boarding or other services",
  //     placeholder: "",
  //     breakpoint: 12,
  //     multiline: true,
  //     rows: 4,
  //     validation: { required: true },
  //     pattern: /^[a-zA-Z ]*$/,
  //     requiredField: true,
  //
  //     error_message: "First Text",
  //     validation_error_message: "Text is in Invalid format",
  //   },
  {
    isRadioAction: true,
    name: "oral_medication",
    label: "Can provide oral medication?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "first_aid",
    label: "Can you provide first aid?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "do_you_have_kids_at_home",
    label: "Do you have kids at home?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "do_you_have_other_pets_at_home",
    label: "Do you have other pets at home?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
];
export const DefaultPHBAboutYouValues = {
  professional_status: "",
  years_of_experience: "",
  tell_us_somthing_about_you: "",
  tell_us_about_the_type_of_pet_and_your_experience: "",
  oral_medication: "",
  first_aid: "",
  do_you_have_kids_at_home: "",
  do_you_have_other_pets_at_home: "",
};
