export const PHBRulesAmentiesEntries = [
  {
    isCustomTypography: true,
    name: "",
    text: "Amenties",
    breakpoint: 12,
    customClass: "login_header",
  },
  {
    isRadioAction: true,
    name: "do_you_have_deticated_boardng_area_for_pets",
    label: "Do you have dedicated boarding area for pets?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "pets_allowed_on_beds",
    label: "Are Pets allowed on Beds?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "do_you_ac_in_pet_sleeping_area",
    label: "Do you A/C  in pet sleeping area?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "pets_allowed_on_furniture",
    label: "Pets allowed on Furniture?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "do_you_have_cctv_at_your_boarding_space",
    label: "Do you have CCTV at your boarding space?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "do_you_have_a_playing_area_for_pets",
    label: "Do you have a playing area for pets?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },

  {
    isRadioAction: true,
    name: "do_you_have_openspace_at_your_boarding_space",
    label: "Do you have outdoor/open space at your boarding space?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },

  {
    isRadioAction: true,
    name: "do_you_provide_first_aid",
    label: "Do you provide first aid?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isCustomTypography: true,
    name: "",
    text: "Rules",
    breakpoint: 12,
    customClass: "login_header",
  },
  {
    isRadioAction: true,
    name: "pet_should_be_vaccinated",
    label: "Pet should be Vaccinated?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },

  {
    isRadioAction: true,
    name: "pet_should_be_potty_trained",
    label: "Pet should be potty Trained?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },

  {
    isCustomTypography: true,
    name: "",
    text: "What offered free as part of Boarding Charges",
    breakpoint: 12,
    customClass: "login_header",
  },

  {
    isRadioAction: true,
    name: "cuddle_time",
    label: "Cuddle Time",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "meals_included_in_boarding_charges",
    label: "Meals Included in Boarding Charges?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "walking",
    label: "Walking",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },

  {
    isCheckBoxAction: true,
    name: "meal_type",
    label: "Meal Type",
    breakpoint: 6,
    checkBoxData: [
      { id: 0, name: "Veg" },
      { id: 1, name: "Non-Veg" },
    ],

    // pattern: /^[A-Za-z][A-Za-z0-9_]{7,29}$/,
    // requiredField: true,
    validation: { required: true },
    error_message: "This field is required",
  },

  {
    isRadioAction: true,
    name: "play_time",
    label: "Play Time",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "dedicated_pet_sitter_during_boarding_time",
    label: "Dedicated pet sitter during Boarding time",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "periodic_update_about_pets",
    label: "Periodic update about Pets (Photos, Videos)",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isTextInput: true,
    name: "what_you_provide_in_meals_as_your_boarding",
    label: "What you provide in meals as of your boarding",

    placeholder: "Individual House",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    multiline: true,
    rows: 2,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "anything_else_is_provided",
    label: "Anything else is provided?",

    placeholder: "Individual House",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    multiline: true,
    rows: 2,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
];
export const DefaultPHBRulesAmentiesValues = {
  do_you_have_deticated_boardng_area_for_pets: "",
  do_you_have_a_playing_area_for_pets: "",
  do_you_ac_in_pet_sleeping_area: "",
  do_you_have_cctv_at_your_boarding_space: "",
  do_you_have_openspace_at_your_boarding_space: "",
  do_you_provide_first_aid: "",
  pets_allowed_on_beds: "",
  pets_allowed_on_furniture: "",
  pet_should_be_vaccinated: "",
  pet_should_be_potty_trained: "",
  cuddle_time: "",
  walking: "",
  play_time: "",
  dedicated_pet_sitter_during_boarding_time: "",
  periodic_update_about_pets: "",
  meals_included_in_boarding_charges: "",
  meal_type: "",
  what_you_provide_in_meals_as_your_boarding: "",
  anything_else_is_provided: "",
};
