export const PetHostAddOnEntries = [
  {
    isTextInput: true,
    name: "AddOnPackage",
    label: "Name Of Your Add On Package",
    placeholder: "Enter Package Name",
    breakpoint: 11,
    value: "state",
    type: "text",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
  },

  {
    isSubmitButton: true,
    name: "add_button",
    buttonTitle: "+",
    breakpoint: 1,
    customClass: "sourceButton",
  },

  {
    isTextInput: true,
    name: "WhatisIncluded",
    label: "What is Included ?",
    placeholder: "List what are included with the package",
    breakpoint: 12,
    value: "state",
    type: "text",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
    multiline: true,
    rows: 2,
  },
  {
    isTextInput: true,
    name: "Rate",
    label: "Rate",
    placeholder: "Enter the rate of packages",
    breakpoint: 12,
    value: "state",
    type: "text",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
  },

  {
    isEmptySpace: true,
    breakpoint: 10,
    name: "space",
  },
  // {
  //   isSubmitButton: true,
  //   name: "submit_button",
  //   buttonTitle: "Save & Submit",
  //   breakpoint: 2,
  //   customClass: "sourceButton",
  // },
];
export const DefaultPetHostAddOnValues = {
  AddOnPackage: "",
  add_button: "",
  WhatisIncluded: "",
  Rate: "",
};
