export const PetHostBasicDetailsEntries = [
  {
    isTextInput: true,
    name: "NameofPet",
    label: "Your Name",
    placeholder: "Enter Your Name",
    breakpoint: 6,
    value: "state",
    type: "text",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
  },
  {
    isTextInput: true,
    name: "mobile_number",
    label: "Mobile Number",
    breakpoint: 6,
    value: "state",
    type: "number",
    pattern: /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/,
    validation: { required: true },
    validation_error_message: "Mobile number must be 10 digits.",
    requiredField: true,
    error_message: "Mobile Number",
  },
  // {
  //   isRadioAction: true,
  //   name: "Gender",
  //   label: "Gender",
  //   breakpoint: 6,
  //   radioButtonData: [{ name: "Male" }, { name: "Female" }, { name: "Others" }],

  //   validation: { required: true },
  //   error_message: "Status",
  // },
  {
    isRadioAction: true,
    name: "Status1",
    label: "Do you have dedicated boarding area for pets?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isBirthdayPicker: true,
    name: "dob",
    date: true,
    label: "Date of Birth",
    placeholder: "DD-MM-YYYY",
    pattern: /^\d{2}-[a-zA-Z]{3}-\d{4}$/,
    breakpoint: 6,
    validation_error_message: "Date of Birth is in Invalid format",
    validation: { required: true },
    requiredField: true,
    error_message: "Date of Birth",
  },
  {
    isTextInput: true,
    name: "NameOfYourPetBoardingSpace",
    label: "Name Of Your Pet Boarding Space",
    placeholder: "Enter Name Of Pet Boarding Space",
    breakpoint: 6,
    type: "text",
    value: "state",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
  },
  {
    isTextInput: true,
    name: "Address",
    label: "Address",
    breakpoint: 6,
    type: "text",
    customClass: "",
    value: "state",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
    multiline: true,
    rows: 2,
  },
  {
    isTextInput: true,
    name: "City",
    label: "City",
    placeholder: "Enter Your City",
    breakpoint: 6,
    type: "text",
    value: "state",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
  },
  {
    isTextInput: true,
    name: "State",
    label: "State",
    placeholder: "Enter Your State",
    breakpoint: 6,
    type: "text",
    value: "state",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
  },
  {
    isTextInput: true,
    name: "Locality",
    label: "Locality",
    placeholder: "Enter Your Locality",
    breakpoint: 6,
    type: "text",
    value: "state",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
  },
  {
    isTextInput: true,
    name: "Pincode",
    label: "Pincode",
    breakpoint: 6,
    value: "state",
    type: "number",
    pattern: /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/,
    validation: { required: true },
    validation_error_message: "Mobile number must be 10 digits.",
    requiredField: true,
    error_message: "Mobile Number",
  },
  {
    isEmptySpace: true,
    breakpoint: 11,
    name: "space",
  },
  // {
  //   isSubmitButton: true,
  //   name: "submit_button",
  //   buttonTitle: "Submit",
  //   breakpoint: 1,
  //   customClass: "sourceButton",
  // },
];

export const DefaultPetHostBasicDetailsValues = {
  NameofPet: "",
  mobile_number: "",
  Status1: "",
  dob: "",
  NameOfYourPetBoardingSpace: "",
  Address: "",
  City: "",
  State: "",
  Locality: "",
  Pincode: "",
};
