export const petHostEntries = [
  {
    isRadioAction: true,
    name: "Status1",
    label: "Do you have dedicated boarding area for pets?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
    },
  
  {
    isRadioAction: true,
    name: "Status2",
    label: "Do you have kids at home?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Status3",
    label: "Do you have a playing area for pets?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Status4",
    label: "Pets allowed on Beds?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Status5",
    label: "Do you A/C  in pet sleeping area?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Status6",
    label: "Pets allowed on Furniture?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Status7",
    label: "Do you have other pets at home?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },

  {
    isRadioAction: true,
    name: "Status8",
    label: "Do you have other pets at home?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },

  {
    isRadioAction: true,
    name: "Status9",
    label: "Do you A/C in pet sleeping area?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },

  {
    isRadioAction: true,
    name: "Status10",
    label: "Pet should be Vaccinated?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isCustomTypography: true,
    name: 'basic_details',
    text: 'What offered free as part of Boarding Charges',
    breakpoint: 12,
    customClass: 'login_header',
  },
  // {
  //   isEmptySpace: true,
  //   breakpoint: 6,
  //   name: 'space',
  // },
  {
    isRadioAction: true,
    name: "Status11",
    label: "Food",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Status12",
    label: "Meals Included in Boarding Changes?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Status13",
    label: "Cuddle Time",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  // {
  //   isCustomTypography: true,
  //   name: 'basic_details',
  //   text: 'What offered free as part of Boarding Charges',
  //   breakpoint: 6,
  //   customClass: 'login_header',
  // },

  {
    isRadioAction: true,
    name: "Status14",
    label: "Veg",
    breakpoint: 3,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
 
  {
    isRadioAction: true,
    name: "Status15",
    label: "Walking",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  //   {
  //   isEmptySpace: true,
  //   breakpoint: 6,
  //   name: 'space',
  // },
  {
    isRadioAction: true,
    name: "Status16",
    label: "Non-Veg",
    breakpoint: 3,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Status17",
    label: "Play Time",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isEmptySpace: true,
    breakpoint: 6,
    name: 'space',
  },
  {
    isRadioAction: true,
    name: "Status18",
    label: "Dedicated pet sitter during Boarding time",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  // {
  //   isTextInput: true,
  //   name: 'ThirdText',
  //   label: 'What you provide in meals as of your boarding',
  //   // placeholder: 'Name',
  //   breakpoint: 5,
  //   validation: { required: true },
  //   pattern: /^.{5,100}$/,
  //   validation_error_message: 'Valid upto 100 characters only !',
  //   requiredField: true,
  //   multiline: true,
  //   rows: 2,
  //   error_message: 'Sub Content',
  // },
  {
    isTextInput: true,
    name: 'firstText',
    label: 'What you provide in meals as of your boarding',
    value:"state",
    placeholder: 'Individual House',
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: 'textBox',
    error_message: 'First Text',
    validation_error_message: 'Text is in Invalid format',
},
  {
    isRadioAction: true,
    name: "Status19",
    label: "Periodic update about pets",
    breakpoint: 6,
    radioButtonData: [{ name: "Photos" }, { name: "Videos" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  // {
  //     isSubmitButton: true,
  //     name: 'submit_button',
  //     buttonTitle: 'Submit',
  //     breakpoint: 1,
  //   },
];
export const DefaultPetHostValues = {
  Status1: "",
  Status2: "",
  Status3: "",
  Status4: "",
  Status5: "",
  Status6: "",
  Status7: "",
  Status8: "",
  Status9: "",
  Status10: "",
  Status11: "",
  Status12: "",
  Status13:"",
  Status14:"",
  Status15:"",
  Status16:"",
  Status17:"",
  Status18:"",
  Status19:"",
  firstText:""
  // submit_button: '',
  // cancel_button: '',
};
