export const PetHostAboutYouEntries = [
  {
    isTextInput: true,
    name: "ProfessionalStatus",
    label: "Professional Status",
    placeholder: "Enter Your Profession",
    breakpoint: 6,
    value: "state",
    customClass: "textBox",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
  },
  {
    isTextInput: true,
    name: "LiveAloneOrWithFamily",
    label: "Live Alone Or With Family ?",
    placeholder: "Enter Details",
    breakpoint: 6,
    type: "text",
    value: "state",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
  },
  {
    isTextInput: true,
    name: "Aboutyou",
    label: "Tell us something about you and your passion towards pet",
    breakpoint: 12,
    type: "text",
    value: "state",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
    multiline: true,
    rows: 2,
  },
  {
    isTextInput: true,
    name: "aboutthepet",
    label:
      "Tell us about the type of pet you have and your experience in boarding or other services",
    breakpoint: 12,
    type: "text",
    value: "state",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
    multiline: true,
    rows: 2,
  },
  {
    isTextInput: true,
    name: "aboutthepettype",
    label:
      "Tell us about the type of pet you have and your experience in boarding or other services",
    breakpoint: 12,
    value: "state",
    type: "text",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
    multiline: true,
    rows: 2,
  },
  {
    isRadioAction: true,
    name: "OralMedication",
    label: "Can You Provide Oral Medication ?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "No",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "FirstAid",
    label: "Can You Provide First Aid ?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "No",
    validation: { required: true },
    error_message: "Status",
  },

  {
    isEmptySpace: true,
    breakpoint: 11,
    name: "space",
  },
  // {
  //   isSubmitButton: true,
  //   name: "submit_button",
  //   buttonTitle: "Submit",
  //   breakpoint: 1,
  //   customClass: "sourceButton",
  // },
];
export const DefaultPetHostAboutYouValues = {
  ProfessionalStatus: "",
  LiveAloneOrWithFamily: "",
  Aboutyou: "",
  aboutthepet: "",
  aboutthepettype: "",
  OralMedication: "",
  FirstAid: "",
};
