export const petHostEntries = [
  {
    isRadioAction: true,
    name: "Status1",
    label: "Do you have dedicated boarding area for pets?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
    },
  
  {
    isRadioAction: true,
    name: "Status2",
    label: "Do you have kids at home?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Status3",
    label: "Do you have a playing area for pets?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Status4",
    label: "Pets allowed on Beds?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Status5",
    label: "Do you A/C  in pet sleeping area?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Status6",
    label: "Pets allowed on Furniture?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Status7",
    label: "Do you have other pets at home?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },

  {
    isRadioAction: true,
    name: "Status8",
    label: "Do you have other pets at home?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },

  {
    isRadioAction: true,
    name: "Status9",
    label: "Do you A/C in pet sleeping area?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },

  {
    isRadioAction: true,
    name: "Status10",
    label: "Pet should be Vaccinated?",
    breakpoint: 6,
    radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  // {
  //     isSubmitButton: true,
  //     name: 'submit_button',
  //     buttonTitle: 'Submit',
  //     breakpoint: 1,
  //   },
];
export const DefaultPetHostValues = {
  Status1: "",
  Status2: "",
  Status3: "",
  Status4: "",
  Status5: "",
  Status6: "",
  Status7: "",
  Status8: "",
  Status9: "",
  Status10: "",
  // submit_button: '',
  // cancel_button: '',
};
