import { useNavigate } from "react-router";
// eslint-disable-next-line react-hooks/rules-of-hooks
// const navigate = useNavigate();
// const onAddAnother = () => {
//   navigate("./AddYourPetLogin")
// };
export const RequestPlace = [
  {
    isTextInput: true,
    name: "street",
    label: "Street",
    placeholder: "Street",
    breakpoint: 4,
    validation: { required: true },
    pattern: /^([a-z0-9])(\w)+([a-z0-9])$/i,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "city",
    label: "City",
    placeholder: "City",
    breakpoint: 4,
    validation: { required: true },
    pattern: /^([a-z0-9])(\w)+([a-z0-9])$/i,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "district",
    label: "District",
    placeholder: "District",
    breakpoint: 4,
    validation: { required: true },
    pattern: /^([a-z0-9])(\w)+([a-z0-9])$/i,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "state",
    label: "State",
    placeholder: "State",
    breakpoint: 4,
    validation: { required: true },
    pattern: /^([a-z0-9])(\w)+([a-z0-9])$/i,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "pincode",
    label: "Pin Code",
    placeholder: "Pin Code",
    breakpoint: 4,
    validation: { required: true },
    pattern: /^([a-z0-9])(\w)+([a-z0-9])$/i,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "pinlocation",
    label: "Pin Location",
    placeholder: "Pin Location",
    breakpoint: 4,
    validation: { required: true },
    pattern: /^([a-z0-9])(\w)+([a-z0-9])$/i,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
];

export const specificRequestEntries = [
  {
    isTextInput: true,
    name: "specific_request",
    label: "Do you have any specific request for your pet",
    placeholder: "Enter Name",
    breakpoint: 12,
    validation: { required: true },
    pattern: /^([a-z0-9])(\w)+([a-z0-9])$/i,
    requiredField: true,
    multiline: true,
    rows: 3,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
];
export const RequestServiceBookingEntries = [
  {
    isCustomTypography: true,
    name: "name1",
    text: "Booking Details",
    breakpoint: 12,
    customClass: "HeaderRED",
  },
  {
    isDropdown: true,
    name: "pet_details",
    labelText: "Select Pet",
    placeholder: "Select Profession",
    DropdownData: [],
    breakpoint: 2.5,
    disabled: true,
    validation: { required: true },
  },
  {
    isAddButton: true,
    name: "name7",
    buttonTitle: "+",
    breakpoint: 0.5,
    // onClickHandle:{onAddAnother},
    customClass: "Addbtn",
    color: "primary",
  },
  {
    isEmptySpace: true,
    breakpoint: 3,
    name: "space",
  },
  // {
  //   isMultipleSelectChip: true,
  //   name: "name2",
  //   breakpoint: 6,
  //   label: "Select Pet",
  //   labelText: "Select Pet",
  //   dropPlaceholder: "Select Pet",
  //   disabled: true,
  //   DropdownData: [
  //     {
  //       id: 1,
  //       value: "Cartomancy",
  //     },
  //     {
  //       id: 2,
  //       value: "Face Reading",
  //     },
  //     {
  //       id: 3,
  //       value: "Lal Kitab",
  //     },
  //     {
  //       id: 4,
  //       value: "Life Coach",
  //     },
  //     {
  //       id: 5,
  //       value: "Loshu Grid",
  //     },
  //   ],
  //   validation: { required: true },
  //   error_message: "Primary Skills",
  // },
  {
    isBirthdayPicker: true,
    name: "booking_date",
    date: true,
    label: "From Date",
    placeholder: "Select Date",
    pattern: /^\d{2}-[a-zA-Z]{3}-\d{4}$/,
    breakpoint: 3,
    validation_error_message: "Date of Birth is in Invalid format",
    validation: { required: true },
    requiredField: true,
    // maxDate: "11/02/2004",
    error_message: "Date of Birth",
  },
  {
    isDateTimePicker: true,
    date: true,
    name: "booking_time",
    label: "Tentative timing",
    error_message: "Interview time is required.",
    breakpoint: 3,
    placeholder: "Eg: 10:00 AM",
    validation: { required: true },
    requiredField: true,
  },
  {
    isEmptySpace: true,
    breakpoint: 6,
    name: "space",
  },
  {
    isRadioAction: true,
    name: "place",
    label: "I want the service provided at?",
    breakpoint: 6,
    radioButtonData: [{ name: "provider's space" }, { name: "My Place" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Gender",
  },

  //   {
  //     isEmptySpace: true,
  //     breakpoint: 6,
  //     name: "space",
  //   },
  {
    isEmptySpace: true,
    breakpoint: 4,
    name: "space",
  },
  {
    isSubmitButton: true,
    name: "name7",
    buttonTitle: "Submit Booking Request",
    breakpoint: 6,
    customClass: "sourceButton",
  },
];

export const RequestTaxiServiceBookingEntries = [
  {
    isCustomTypography: true,
    name: "name1",
    text: "Booking Details",
    breakpoint: 12,
    customClass: "HeaderRED",
  },
  {
    isDropdown: true,
    name: "pet_details",
    labelText: "Select Pet",
    placeholder: "Select Profession",
    DropdownData: [],
    breakpoint: 2.5,
    disabled: true,
    validation: { required: true },
  },
  {
    isAddButton: true,
    name: "name7",
    buttonTitle: "+",
    breakpoint: 0.5,
    // onClickHandle:{onAddAnother},
    customClass: "Addbtn",
    color: "primary",
  },
  {
    isEmptySpace: true,
    breakpoint: 3,
    name: "space",
  },

  {
    isBirthdayPicker: true,
    name: "booking_date",
    date: true,
    label: "From Date",
    placeholder: "Select Date",
    pattern: /^\d{2}-[a-zA-Z]{3}-\d{4}$/,
    breakpoint: 3,
    validation_error_message: "Date of Birth is in Invalid format",
    validation: { required: true },
    requiredField: true,
    // maxDate: "11/02/2004",
    error_message: "Date of Birth",
  },
  {
    isDateTimePicker: true,
    date: true,
    name: "booking_time",
    label: "Tentative timing",
    error_message: "Interview time is required.",
    breakpoint: 3,
    placeholder: "Eg: 10:00 AM",
    validation: { required: true },
    requiredField: true,
  },
  {
    isEmptySpace: true,
    breakpoint: 6,
    name: "space",
  },
  {
    isTextInput: true,
    name: "Pic_kup_Location",
    label: "Pick up Location",
    placeholder: "Enter Name",
    breakpoint: 3,
    validation: { required: true },
    pattern: /^([a-z0-9])(\w)+([a-z0-9])$/i,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "Drop",
    label: "Drop",
    placeholder: "Enter Name",
    breakpoint: 3,
    validation: { required: true },
    pattern: /^([a-z0-9])(\w)+([a-z0-9])$/i,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isEmptySpace: true,
    breakpoint: 6,
    name: "space",
  },
  {
    isDropdown: true,
    name: "Vehicle_type",
    labelText: "Vehicle type",
    placeholder: "Select Profession",
    DropdownData: [],
    breakpoint:3,
    disabled: true,
    validation: { required: true },
  },
  {
    isRadioAction: true,
    name: "place",
    label: "vehicle",
    breakpoint: 3,
    radioButtonData: [{ name: "A/C" }, { name: "Non A/C" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Gender",
  },
]

export const DefaultRequestServiceBookingValues = {
  name1: "",
  name2: "",
  name3: "",
  name4: "",
  name6: "",
  name7: "",
  fourthText: "",
};
