export const AddressEntries = [
  //   {
  //     isEmptySpace: true,
  //     breakpoint: 1,
  //     name: "space",
  //   },
  // {
  //   isTextInput: true,
  //   name: "Your_Name",
  //   label: "Your Name",
  //   placeholder: "Your Name",
  //   breakpoint: 4,
  //   validation: { required: true },
  //   pattern: /^[a-zA-Z ]*$/,
  //   requiredField: true,
  //   customClass: "textBox",
  //   error_message: "First Text",
  //   validation_error_message: "Text is in Invalid format",
  // },
  // {
  //   isTextInput: true,
  //   name: "Mobile_number",
  //   label: "Mobile number",
  //   placeholder: "Enter Mobile_number",
  //   breakpoint: 4,
  //   validation: { required: true },
  //   pattern: /^[a-zA-Z ]*$/,
  //   requiredField: true,
  //   customClass: "textBox",
  //   error_message: "First Text",
  //   validation_error_message: "Text is in Invalid format",
  // },
  // {
  //   isTextInput: true,
  //   name: "Email",
  //   label: "Email",
  //   placeholder: "Enter Email",
  //   breakpoint: 4,
  //   validation: { required: true },
  //   pattern: /^[a-zA-Z ]*$/,
  //   requiredField: true,
  //   customClass: "textBox",
  //   error_message: "First Text",
  //   validation_error_message: "Text is in Invalid format",
  // },
  // {
  //   isRadioAction: true,
  //   name: "Gender",
  //   label: "Gender",
  //   breakpoint: 4,
  //   radioButtonData: [{ name: "Photos" }, { name: "Videos" }],
  //   validation: { required: true },
  //   requiredField: true,
  //   error_message: "Status",
  // },
  // {
  //   isEmptySpace: true,
  //   breakpoint: 8,
  //   name: "space",
  // },
  {
    isTextInput: true,
    name: "Street",
    label: "Street",
    placeholder: "Enter Door no, Street Name, Block",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "Street",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "Locality",
    label: "Locality",
    placeholder: "Enter Locality",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "Locality",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "City",
    label: "City",
    placeholder: "Enter Your City",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "City",
    validation_error_message: "Text is in Invalid format",
  },

  //   {
  //     isEmptySpace: true,
  //     breakpoint: 1.05,
  //     name: "space",
  //   },
  {
    isTextInput: true,
    name: "State",
    label: "State",
    placeholder: "Enter State",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "State",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "Pincode",
    label: "Pincode",
    placeholder: "Enter Pincode",
    breakpoint: 6,
    type: "number",
    validation: { required: true },
    pattern: "/^(+d{1,3}[- ]?)?d{6}$/",
    requiredField: true,
    customClass: "textBox",
    error_message: "Pincode",
    validation_error_message: "Text is in Invalid format",
  },

  //   {
  //     isEmptySpace: true,
  //     breakpoint: 1,
  //     name: "space",
  //   },

  // {
  //   isTextInput: true,
  //   name: "Location",
  //   label: " Pin Location",
  //   placeholder: "Enter Location",
  //   breakpoint: 6,
  //   validation: { required: true },
  //   pattern: /^[a-zA-Z ]*$/,
  //   requiredField: true,
  //   customClass: "textBox",
  //   error_message: "Location",
  //   validation_error_message: "Text is in Invalid format",
  // },

  {
    isEmptySpace: true,
    breakpoint: 6.3,
    name: "space",
  },
  {
    isSubmitButton: true,
    name: "submit_button",
    buttonTitle: "Next",
    breakpoint: 3,
    customClass: "sourceButton",
  },
];
export const DefaultAddressEntriesValues = {
  Street: "",
  City: "",
  Locality: "",
  State: "",
  Pincode: "",
  // Location: "",
  submit_button: "",
};
