export const AddressEntries = [
  //   {
  //     isEmptySpace: true,
  //     breakpoint: 1,
  //     name: "space",
  //   },
  {
    isTextInput: true,
    name: "Street",
    label: "Street",
    placeholder: "Enter Door no, Street Name, Block",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "City",
    label: "City",
    placeholder: "Enter Your City",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  //   {
  //     isEmptySpace: true,
  //     breakpoint: 1.05,
  //     name: "space",
  //   },
  {
    isTextInput: true,
    name: "Locality",
    label: "Locality",
    placeholder: "Enter Locality",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },

  {
    isTextInput: true,
    name: "State",
    label: "State",
    placeholder: "Enter State",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  //   {
  //     isEmptySpace: true,
  //     breakpoint: 1,
  //     name: "space",
  //   },
  {
    isTextInput: true,
    name: "Pincode",
    label: "Pincode",
    placeholder: "Enter Pincode",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "Location",
    label: "Location",
    placeholder: "Enter Location",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },

  {
    isEmptySpace: true,
    breakpoint: 6.3,
    name: "space",
  },
  {
    isSubmitButton: true,
    name: "submit_button",
    buttonTitle: "Next",
    breakpoint: 5.6,
    customClass: "sourceButton",
  },
];
export const DefaultAddressEntriesValues = {
  Street: "",
  City: "",
  Locality: "",
  State: "",
  Pincode: "",
  Location: "",
  submit_button: "",
};
