export const RegisterEntries = [
  {
    isFileUploader: true,
    name: "fileUploader",
    label: "Add Photos",
    breakpoint: 12,
    customClass: "uploadImageContainer",
    validation: { required: true },
    error_message: "Upload Image",
  },
  // {
  //   isEmptySpace: true,
  //   breakpoint: { xl: 1, lg: 1, md: 1.05, sm: 0, xs: 0 },
  //   name: "space",
  // },
  {
    isTextInput: true,
    name: "YourName",
    label: "Your Name",
    placeholder: "Enter Your Name",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "Your Name",
    validation_error_message: "Name is in Invalid format",
  },
  {
    isRadioAction: true,
    name: "Gender",

    label: "Gender",
    breakpoint: 6,
    radioButtonData: [{ name: "Male" }, { name: "Female" }, { name: "Others" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Gender",
  },
  {
    isTextInput: true,
    name: "Email",
    label: "Email",
    placeholder: "Enter Your Email",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "Email",
    validation_error_message: "Email is in Invalid format",
  },
  {
    isTextInput: true,
    name: "MobileNumber",
    label: "Mobile Number",
    placeholder: "Enter Your Mobile Number",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^(\+?\d{1,4}[\s-])?(?!0+\s+,?$)\d{10}\s*,?$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "Mobile Number",
    validation_error_message: "Mobile Number is in Invalid format",
  },
  // {
  //   isEmptySpace: true,
  //   breakpoint: { xl: 1.05, lg: 1.05, md: 1.05, sm: 0, xs: 0 },
  //   name: "space",
  // },

  // {
  //   isEmptySpace: true,
  //   breakpoint: { xl: 1, lg: 1, md: 0, sm: 0, xs: 0 },
  //   name: "space",
  // },
  {
    isTextInput: true,
    name: "Password",
    label: "Password",
    placeholder: "Enter Your Password",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "Password",
    validation_error_message: "Password is in Invalid format",
  },
  {
    isTextInput: true,
    name: "ConfirmPassword",
    label: "Confirm Password",
    placeholder: "Confirm Password",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "Confirm Password",
    validation_error_message: "Confirm Password is in Invalid format",
  },
  {
    isEmptySpace: true,
    breakpoint: 6.3,
    name: "space",
  },
  {
    isSubmitButton: true,
    name: "submit_button",
    buttonTitle: "Next",
    breakpoint: 5.6,
    customClass: "sourceButton",
  },
];

export const DefaultRegisterEntriesValues = {
  fileUploader: "",
  YourName: "",
  MobileNumber: "",
  Gender: "",
  Email: "",
  Password: "",
  ConfirmPassword: "",
  submit_button: "",
};
