export const RegisterEntries = [
  {
    isFileUploader: true,
    name: "fileUploader",
    label: "Add Photos",
    breakpoint: 12,
    customClass: "uploadImageContainer",
    validation: { required: true },
    error_message: "Upload Image",
  },
  // {
  //   isEmptySpace: true,
  //   breakpoint: { xl: 1, lg: 1, md: 1.05, sm: 0, xs: 0 },
  //   name: "space",
  // },
  {
    isTextInput: true,
    name: "YourName",
    label: "Your Name",
    placeholder: "Enter Your Name",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "SecondText",
    label: "Mobile Number",
    placeholder: "Enter Your Mobile Number",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  // {
  //   isEmptySpace: true,
  //   breakpoint: { xl: 1.05, lg: 1.05, md: 1.05, sm: 0, xs: 0 },
  //   name: "space",
  // },
  {
    isRadioAction: true,
    name: "Gender",

    label: "Gender",
    breakpoint: 6,
    radioButtonData: [{ name: "Male" }, { name: "Female" }, { name: "Others" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },

  {
    isBirthdayPicker: true,
    name: "dob",
    date: true,
    label: "Date of Birth",
    placeholder: "DD-MM-YYYY",
    pattern: /^\d{2}-[a-zA-Z]{3}-\d{4}$/,
    breakpoint: 6,
    validation_error_message: "Date of Birth is in Invalid format",
    validation: { required: true },
    requiredField: true,
    maxDate: "11/02/2004",
    error_message: "Date of Birth",
  },
  // {
  //   isEmptySpace: true,
  //   breakpoint: { xl: 1, lg: 1, md: 0, sm: 0, xs: 0 },
  //   name: "space",
  // },
  {
    isTextInput: true,
    name: "Password",
    label: "Password",
    placeholder: "Enter Your Password",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "ConfirmPassword",
    label: "Confirm Password",
    placeholder: "Confirm Password",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isEmptySpace: true,
    breakpoint: 6.3,
    name: "space",
  },
  {
    isSubmitButton: true,
    name: "submit_button",
    buttonTitle: "Next",
    breakpoint: 5.6,
    customClass: "sourceButton",
  },
];

export const DefaultRegisterEntriesValues = {
  fileUploader: "",
  YourName: "",
  SecondText: "",
  Gender: "",
  dob: "",
  Password: "",
  ConfirmPassword: "",
  submit_button: "",
};
