export const AddAnotherPetEntries = [
  {
    isTextInput: true,
    name: "PetName",
    label: "Your Pet Name",
    placeholder: "Enter Name",
    breakpoint: 4,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isEmptySpace: true,
    breakpoint: 2,
    name: "space",
  },
  {
    isDropdown: true,
    name: "YourPetType",
    label: "Your Pet Type",
    placeholder: "Select Your Pet Type",
    DropdownData: [
      {
        id: 1,
        value: "Student",
      },
      {
        id: 2,
        value: "Housewife",
      },
      {
        id: 3,
        value: "Professional boarder",
      },
      {
        id: 4,
        value: "Working Professional",
      },
    ],
    breakpoint: 2,
    disabled: true,
    validation: { required: true },
  },
  {
    isDropdown: true,
    name: "YourPetBreed",
    label: "Your Pet Breed",
    placeholder: "Select Breed",
    DropdownData: [
      {
        id: 1,
        value: "Student",
      },
      {
        id: 2,
        value: "Housewife",
      },
      {
        id: 3,
        value: "Professional boarder",
      },
      {
        id: 4,
        value: "Working Professional",
      },
    ],
    breakpoint: 2,
    disabled: true,
    validation: { required: true },
  },
  {
    isRadioAction: true,
    name: "Gender",
    label: "Gender",
    breakpoint: 4,
    radioButtonData: [{ name: "Male" }, { name: "Female" }, { name: "Others" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isEmptySpace: true,
    breakpoint: 2,
    name: "space",
  },
  {
    isBirthdayPicker: true,
    name: "dob",
    date: true,
    label: "Date of Birth",
    placeholder: "DD-MM-YYYY",
    pattern: /^\d{2}-[a-zA-Z]{3}-\d{4}$/,
    breakpoint: 2,
    validation_error_message: "Date of Birth is in Invalid format",
    validation: { required: true },
    requiredField: true,
    maxDate: "11/02/2004",
    error_message: "Date of Birth",
  },
  {
    isDropdown: true,
    name: "Weight",
    label: "Weight",
    placeholder: "Select Weight in Kgs",
    DropdownData: [
      {
        id: 1,
        value: "Student",
      },
      {
        id: 2,
        value: "Housewife",
      },
      {
        id: 3,
        value: "Professional boarder",
      },
      {
        id: 4,
        value: "Working Professional",
      },
    ],
    breakpoint: 2,
    disabled: true,
    validation: { required: true },
  },
  {
    isFileUploader: true,
    name: "fileUploader",
    label: "Add Vaccination Card",
    breakpoint: 4,
    customClass: "uploadImageContainer",
    validation: { required: true },
    error_message: "Upload Image",
  },
  {
    isEmptySpace: true,
    breakpoint: 2,
    name: "space",
  },
  {
    isFileUploader: true,
    name: "fileUploader2",
    label: "Add License",
    breakpoint: 4,
    customClass: "uploadImageContainer",
    validation: { required: true },
    error_message: "Upload Image",
  },
  {
    isTextInput: true,
    name: "description",
    label: "Brief description about the pet",
    placeholder: "Description",
    breakpoint: 4,
    multiline: true,
    rows: 3,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isEmptySpace: true,
    breakpoint: 2,
    name: "space",
  },
  {
    isMultipleSelectChip: true,
    name: "Interests",
    breakpoint: 4,
    label: "Interests",
    labelText: "Interests",
    dropPlaceholder: "Primary Skills",
    disabled: true,
    DropdownData: [
      {
        id: 1,
        value: "Cartomancy",
      },
      {
        id: 2,
        value: "Face Reading",
      },
      {
        id: 3,
        value: "Lal Kitab",
      },
      {
        id: 4,
        value: "Life Coach",
      },
      {
        id: 5,
        value: "Loshu Grid",
      },
    ],
    validation: { required: true },
    error_message: "Primary Skills",
  },
  {
    isTextInput: true,
    name: "WalkingRoutine",
    label: "Walking Routine",
    placeholder: "Select Routine",
    breakpoint: 4,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isEmptySpace: true,
    breakpoint: 2,
    name: "space",
  },
  {
    isTextInput: true,
    name: "FoodPreference",
    label: "Food Preference",
    placeholder: "Preferred Food",
    breakpoint: 4,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isFileUploader: true,
    name: "AddPhotos",
    label: "Add Photos",
    breakpoint: 4,
    customClass: "uploadImageContainer",
    validation: { required: true },
    error_message: "Upload Image",
  },
  {
    isEmptySpace: true,
    breakpoint: 4,
    name: "space",
  },
  {
    isSubmitButton: true,
    name: "submit_button",
    buttonTitle: "Submit",
    breakpoint: 2,
  },
];
export const DefaultAddAnotherPetEntriesValues = {
  PetName: "",
  YourPetType: "",
  YourPetBreed: "",
  Gender: "",
  dob: "",
  Weight: "",
  fileUploader: "",
  fileUploader2: "",
  description: "",
  Interest: "",
  WalkingRoutine: "",
  FoodPreference: "",
  AddPhotos: "",
  submit_button: "",
};
