// import CustomIcons from '../../utils/icon';

export const AddYourPetentries = [
  {
    isTextInput: true,
    name: "pet_name",
    label: "Your Pet Name",
    placeholder: "Enter Name",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },

  {
    isDropdown: true,
    name: "pet_type",
    labelText: "Your Pet Type",
    placeholder: "Select Profession",
    DropdownData: [],
    breakpoint: 3,
    disabled: true,
    validation: { required: true },
  },

  {
    isDropdown: true,
    name: "pet_breed",
    labelText: "Your Pet Breed",
    placeholder: "Select Profession",
    DropdownData: [],
    breakpoint: 3,
    disabled: true,
    validation: { required: true },
  },
  {
    isRadioAction: true,
    name: "gender",
    label: "Gender",
    breakpoint: 6,
    radioButtonData: [{ name: "Male" }, { name: "Female" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isTextInput: true,
    name: "weight",
    label: "weight",
    type: "number",
    placeholder: "Enter Name",
    breakpoint: 6,
    validation: { required: true },
    // pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  // {
  //   isDropdown: true,
  //   name: "weight",
  //   labelText: "Weight",
  //   placeholder: "Select Profession",
  //   DropdownData: [
  //     {
  //       id: 1,
  //       value: "Student",
  //     },
  //     {
  //       id: 2,
  //       value: "Housewife",
  //     },
  //     {
  //       id: 3,
  //       value: "Professional boarder",
  //     },
  //     {
  //       id: 4,
  //       value: "Working Professional",
  //     },
  //   ],
  //   breakpoint: 6,
  //   disabled: true,
  //   validation: { required: true },
  // },
  {
    isBirthdayPicker: true,
    name: "dob",
    date: true,
    label: "Date of Birth",
    placeholder: "DD-MM-YYYY",
    pattern: /^\d{2}-[a-zA-Z]{3}-\d{4}$/,
    breakpoint: 6,
    validation_error_message: "Date of Birth is in Invalid format",
    validation: { required: true },
    requiredField: true,
    maxDate: "11/02/2004",
    error_message: "Date of Birth",
  },
  {
    isFileUploader: true,
    name: "license",
    label: "Add License",
    breakpoint: 3,
    customClass: "uploadImageContainer",
    validation: { required: true },
    error_message: "Upload Image",
  },
  {
    isFileUploader: true,
    name: "vaccination_card",
    label: "Add Vaccination Card",
    breakpoint: 3,
    customClass: "uploadImageContainer",
    validation: { required: true },
    error_message: "Upload Image",
  },
  {
    isTextInput: true,
    name: "description",
    label: "Brief Description about the pet",
    placeholder: "Enter Name",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "interests",
    label: "Interests",
    placeholder: "Enter Name",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "food_preference",
    label: "Food Preference",
    placeholder: "Enter Name",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "walking_routine",
    label: "Making Routine",
    placeholder: "Enter Name",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isFileUploader: true,
    name: "photos",
    label: "Add Photos",
    breakpoint: 3,
    customClass: "uploadImageContainer",
    validation: { required: true },
    error_message: "Upload Image",
  },
  {
    isEmptySpace: true,
    breakpoint: 9,
    name: "space",
  },
  {
    isEmptySpace: true,
    breakpoint: 8,
    name: "space",
  },
  {
    isSubmitButton: true,
    name: "submit_button",
    buttonTitle: "Next",
    breakpoint: 4,
    customClass: "sourceButton",
  },
];
export const DefaultAddYourPetValues = {
  pet_name: "",
  pet_type: "",
  pet_breed: "",
  gender: "",
  weight: "",
  dob: "",
  license: "",
  vaccination_card: "",
  description: "",
  interests: "",
  food_preference: "",
  walking_routine: "",
  photos: "",
  // submit_button: '',
  // cancel_button: '',
};
