// import CustomIcons from '../../utils/icon';

 export const AddYourPetentries = [
    {
        isTextInput: true,
        name: "no_of_pets",
        label: "Your Pet Name",
        placeholder: "Enter Name",
        breakpoint: 6,
        validation: { required: true },
        pattern: /^[a-zA-Z ]*$/,
        requiredField: true,
        customClass: "textBox",
        error_message: "First Text",
        validation_error_message: "Text is in Invalid format",
      },
      {
        isDropdown: true,
        name: "professional_status",
        labelText: "Professional Status",
        placeholder: "Select Profession",
        DropdownData: [
          {
            id: 1,
            value: "Student",
          },
          {
            id: 2,
            value: "Housewife",
          },
          {
            id: 3,
            value: "Professional boarder",
          },
          {
            id: 4,
            value: "Working Professional",
          },
        ],
        breakpoint: 3,
        disabled: true,
        validation: { required: true },
      },
      {
        isDropdown: true,
        name: "professional_status",
        labelText: "Professional Status",
        placeholder: "Select Profession",
        DropdownData: [
          {
            id: 1,
            value: "Student",
          },
          {
            id: 2,
            value: "Housewife",
          },
          {
            id: 3,
            value: "Professional boarder",
          },
          {
            id: 4,
            value: "Working Professional",
          },
        ],
        breakpoint:3,
        disabled: true,
        validation: { required: true },
      },
      {
        isRadioAction: true,
        name: "Status3",
        label: "Do you have a playing area for pets?",
        breakpoint: 6,
        radioButtonData: [{ name: "Active" }, { name: "Inactive" }],
        validation: { required: true },
        requiredField: true,
        error_message: "Status",
    },
    {
        isDropdown: true,
        name: "professional_status",
        labelText: "Professional Status",
        placeholder: "Select Profession",
        DropdownData: [
          {
            id: 1,
            value: "Student",
          },
          {
            id: 2,
            value: "Housewife",
          },
          {
            id: 3,
            value: "Professional boarder",
          },
          {
            id: 4,
            value: "Working Professional",
          },
        ],
        breakpoint: 6,
        disabled: true,
        validation: { required: true },
      },
    {
        isBirthdayPicker: true,
        name: 'dob',
        date: true,
        label: 'Date of Birth',
        placeholder: 'DD-MM-YYYY',
        pattern: /^\d{2}-[a-zA-Z]{3}-\d{4}$/,
        breakpoint: 6,
        validation_error_message: 'Date of Birth is in Invalid format',
        validation: { required: true },
        requiredField: true,
        maxDate: '11/02/2004',
        error_message: 'Date of Birth',
    },
    {
        isFileUploader: true,
        name: "fileUploader",
        label: "Add Photos",
        breakpoint: 3,
        customClass: "uploadImageContainer",
        validation: { required: true },
        error_message: "Upload Image",
    },
    {
        isFileUploader: true,
        name: "fileUploader",
        label: "Add Photos",
        breakpoint: 3,
        customClass: "uploadImageContainer",
        validation: { required: true },
        error_message: "Upload Image",
    },
    {
        isTextInput: true,
        name: "no_of_pets",
        label: "Your Pet Name",
        placeholder: "Enter Name",
        breakpoint: 6,
        validation: { required: true },
        pattern: /^[a-zA-Z ]*$/,
        requiredField: true,
        customClass: "textBox",
        error_message: "First Text",
        validation_error_message: "Text is in Invalid format",
    },
    {
        isTextInput: true,
        name: "no_of_pets",
        label: "Your Pet Name",
        placeholder: "Enter Name",
        breakpoint: 6,
        validation: { required: true },
        pattern: /^[a-zA-Z ]*$/,
        requiredField: true,
        customClass: "textBox",
        error_message: "First Text",
        validation_error_message: "Text is in Invalid format",
    },
    {
        isTextInput: true,
        name: "no_of_pets",
        label: "Your Pet Name",
        placeholder: "Enter Name",
        breakpoint: 6,
        validation: { required: true },
        pattern: /^[a-zA-Z ]*$/,
        requiredField: true,
        customClass: "textBox",
        error_message: "First Text",
        validation_error_message: "Text is in Invalid format",
    },
    {
        isTextInput: true,
        name: "no_of_pets",
        label: "Your Pet Name",
        placeholder: "Enter Name",
        breakpoint: 6,
        validation: { required: true },
        pattern: /^[a-zA-Z ]*$/,
        requiredField: true,
        customClass: "textBox",
        error_message: "First Text",
        validation_error_message: "Text is in Invalid format",
   },
   {
    isFileUploader: true,
    name: "fileUploader",
    label: "Add Photos",
    breakpoint: 3,
    customClass: "uploadImageContainer",
    validation: { required: true },
    error_message: "Upload Image",
},
     {
        isEmptySpace: true,
        breakpoint: 9,
        name: 'space',
   },
   {
    isEmptySpace: true,
    breakpoint: 8,
    name: 'space',
  },
     {
        isSubmitButton: true,
        name: 'submit_button',
        buttonTitle: 'Next',
        breakpoint: 4,
        customClass: 'sourceButton',
      },
  ];
  export const DefaultAddYourPetValues = {
    firstText: "",
    SecondText: "",
    fourthText: "",
    ThirdText: "",
    fifthText: "",
    sixthText: "",
    seventhText: "",
    fileUploader: "",
    pin_code: "",
    location: "",
    // submit_button: '',
    // cancel_button: '',
  };