export const EditMyBoardingSpaceEntries = [
  {
    isEmptySpace: true,
    breakpoint: 9,
    name: "space",
  },
  {
    isFileUploader: true,
    name: "fileUploader",
    label: "Add Photos",
    breakpoint: 3,
    customClass: "uploadImageContainer",
    validation: { required: true },
    error_message: "Upload Image",
  },
  {
    isTextInput: true,
    name: "Nameofyourpetspace",
    label: "Name of your pet space",
    placeholder: "Enter You Pet Space",
    breakpoint: 4,

    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "TotalSqFeetoftheSpace",
    label: "Total Sq Feet of the Space",
    placeholder: "Enter Total Sq Feet",
    breakpoint: 4,

    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "TypeofBoarding",
    label: "Type of Boarding",
    placeholder: "Individual House",
    breakpoint: 4,

    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },

  {
    isMultipleSelectChip: true,
    name: "CategoryofPetsBoarded",
    breakpoint: 4,
    label: "Category of Pets Boarded",
    labelText: "Category of Pets Boarded",
    dropPlaceholder: "Select Pet",
    disabled: true,
    DropdownData: [
      {
        id: 1,
        value: "Cartomancy",
      },
      {
        id: 2,
        value: "Face Reading",
      },
      {
        id: 3,
        value: "Lal Kitab",
      },
      {
        id: 4,
        value: "Life Coach",
      },
      {
        id: 5,
        value: "Loshu Grid",
      },
    ],
    validation: { required: true },
    error_message: "Primary Skills",
  },
  {
    isTextInput: true,
    name: "PriceforPerDayBoardingHours",
    label: "Price for Per Day Boarding(24 Hours)",
    placeholder: "Enter Price",
    breakpoint: 4,

    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },

  {
    isTextInput: true,
    name: "NoofpetsBoardingCapacity",
    label: "No of pets (Boarding Capacity)",
    placeholder: "Enter Number",
    breakpoint: 4,

    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },

  {
    isTextInput: true,
    name: "NoofBedRooms",
    label: "No of Bed Rooms",
    placeholder: "No of Bed Rooms",
    breakpoint: 4,

    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },

  {
    isTextInput: true,
    name: "Howmanypetscanyouhostatmax",
    label: "How many pets can you host at max ?",
    placeholder: "Enter a Number",
    breakpoint: 4,

    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },

  {
    isTextInput: true,
    name: "PriceforDayCareBoarding",
    label: "Price for Day Care(Boarding)",
    placeholder: "Enter Price",
    breakpoint: 4,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },

  {
    isTextInput: true,
    name: "Address",
    label: "Address",
    placeholder: "",
    breakpoint: 4,
    multiline: true,
    rows: 3,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },

  {
    isTextInput: true,
    name: "City",
    label: "City",
    placeholder: "Enter City",
    breakpoint: 4,

    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },

  {
    isTextInput: true,
    name: "State",
    label: "State",
    placeholder: "Enter State",
    breakpoint: 4,

    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },

  {
    isTextInput: true,
    name: "PinLocation",
    label: "Pin Location",
    placeholder: "Enter Location",
    breakpoint: 4,

    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },

  {
    isTextInput: true,
    name: "Locality",
    label: "Locality",
    placeholder: "Enter Locality",
    breakpoint: 4,

    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },

  {
    isTextInput: true,
    name: "Pincode",
    label: "Pincode",
    placeholder: "Enter Pincode",
    breakpoint: 4,

    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },

  {
    isCustomTypography: true,
    name: "Amenties",
    text: "Amenties",

    breakpoint: 12,
    customClass: "Amenties",
  },
  {
    isRadioAction: true,
    name: "dedicatedboardingarea",
    label: "Do you have dedicated boarding area for pets?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "kidsathome",
    label: "Do you have kids at home?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Food",
    label: "Food",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "playingarea",
    label: "Do you have a playing area for pets?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Beds",
    label: "Pets allowed on Beds?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "CuddleTime",
    label: "Cuddle Time",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },

  {
    isRadioAction: true,
    name: "A/C",
    label: "Do you A/C in pet sleeping area?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Furniture",
    label: "Pets allowed on Furniture?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Walking",
    label: "Walking",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "other pets",
    label: "Do you have other pets at home?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Pets allowed",
    label: "Pets allowed on Beds?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Play time",
    label: "Play time",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },

  {
    isRadioAction: true,
    name: "dedicated boarding area",
    label: "Do you have dedicated boarding area for pets?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "kids at home",
    label: "Do you have kids at home?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Food",
    label: "Food",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "playing area",
    label: "Do you have a playing area for pets?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Beds",
    label: "Pets allowed on Beds?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Cuddle Time",
    label: "Cuddle Time",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },

  {
    isRadioAction: true,
    name: "AC",
    label: "Do you A/C in pet sleeping area?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Furniture",
    label: "Pets allowed on Furniture?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Walking",
    label: "Walking",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "otherpets",
    label: "Do you have other pets at home?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Petsallowed",
    label: "Pets allowed on Beds?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Playtime",
    label: "Play time",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isCustomTypography: true,
    name: "Food",
    text: "Food",

    breakpoint: 12,
    customClass: "Meals",
    customClass1: "Food",
  },
  {
    isRadioAction: true,
    text: "What Provided In Meals",
    customClass: "Meals",
    name: "Veg",
    label: "Veg",
    name2: "NonVeg",
    label2: "Non-Veg",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    radioButtonData2: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "No",
    validation: { required: true },
    error_message: "Status",
  },

  //   {
  //     isCustomTypography: true,
  //     name: "WhatyouProvidedInMealsasofYourBoarding",
  //     text: "What you Provided In Meals as of Your Boarding",

  //     breakpoint: 4,
  //     customClass: "Meals",
  //     customClass1: "Food",
  //   },
  {
    isTextInput: true,
    name: "WhatyouProvidedInMealsasofYourBoarding",
    label: "What you Provided In Meals as of Your Boarding",
    placeholder: "Pedigree",
    breakpoint: 4,

    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isEmptySpace: true,
    breakpoint: 9,
    name: "space",
  },
  {
    isSubmitButton: true,
    name: "name7",
    buttonTitle: "Save & Submit",
    breakpoint: 2,
    // customClass: "sourceButton",
  },
];

export const DefaultEditMyBoardingSpaceValues = {
  fileUploader: "",
  Nameofyourpetspace: "",
  TotalSqFeetoftheSpace: "",
  TypeofBoarding: "",
  CategoryofPetsBoarded: "",
  PriceforPerDayBoardingHours: "",
  dedicatedboardingarea: "",
  NoofpetsBoardingCapacity: "",
  NoofBedRooms: "",
  Howmanypetscanyouhostatmax: "",
  PriceforDayCareBoarding: "",
  Address: "",
  City: "",
  State: "",
  PinLocation: "",
  Locality: "",
  Pincode: "",
  kidsathome: "",
  Food: "",
  playingarea: "",
  Beds: "",
  CuddleTime: "",
  AC: "",
  Furniture: "",
  Walking: "",
  otherpets: "",
  Petsallowed: "",
  Playtime: "",
  submit_button: "",
  WhatProvidedInMeals: "",
  WhatyouProvidedInMealsasofYourBoarding: "",
  Veg: "",
  NonVeg: "",
};
