export const PBRBasicDetailsEntries = [
  {
    isFileUploader: true,
    name: "image",
    label: "Add Photos",
    breakpoint: 12,
    customClass: "uploadImageContainer",
    validation: { required: true },
    requiredField: true,
    error_message: "Upload Image",
  },

  {
    isTextInput: true,
    type: "text",
    name: "name",
    label: "Name",
    placeholder: "Enter Name",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^([a-z0-9])(\w)+([a-z0-9])$/i,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },

  {
    isRadioAction: true,
    name: "gender",

    label: "Gender",
    breakpoint: 6,
    radioButtonData: [{ name: "Male" }, { name: "Female" }, { name: "Others" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Gender",
  },
  {
    isTextInput: true,
    type: "email",
    name: "email",
    label: "Email",
    placeholder: "Enter Name",
    breakpoint: 6,
    validation: { required: true },
    pattern:
      /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  // {
  //   isTextInput: true,
  //   name: "email",
  //   label: "Email",
  //   breakpoint: 6,
  //   validation: { required: true },
  //   pattern:
  //     /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/,
  //   requiredField: true,
  //   customClass: "textBox",
  //   validation_error_message: "Text is in Invalid format",
  // },
  {
    isTextInput: true,
    name: "mobile_number",
    type: "text",
    label: "Mobile Number",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^(\+\d{1,3}[- ]?)?\d{10}$/,
    requiredField: true,
    customClass: "textBox",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isPasswordInput: true,
    type: "text",
    name: "password",
    label: "Password",
    breakpoint: 6,

    validation: { required: true },
    pattern: /^(?=.*[0-9])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{6,16}$/,
    requiredField: true,
    customClass: "textBox",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isPasswordInput: true,
    type: "text",
    name: "confirmPassword",
    label: "Confirm Password",
    breakpoint: 6,
    validation: { required: true },

    requiredField: true,
    errorMessage: "not match",
    customClass: "textBox",
    validation_error_message: "Text is in Invalid format",
  },

  // {
  //   isSubmitButton: true,
  //   name: "submit_button",
  //   buttonTitle: "Next",
  //   breakpoint: 5.6,
  //   customClass: "sourceButton",
  // },
];

export const DefaultPBRBasicDetailsEntriesValues = {
  image: "",
  name: "",
  mobile_number: "",
  gender: "",
  email: "",
  password: "",
  confirmPassword: "",
  submit_button: "",
};
