export const AboutPetEntries = [
  {
    isDropdown: true,
    name: "professional_status",
    labelText: "Professional Status",
    placeholder: "Select Profession",
    DropdownData: [
      {
        id: 1,
        value: "Student",
      },
      {
        id: 2,
        value: "Housewife",
      },
      {
        id: 3,
        value: "Professional boarder",
      },
      {
        id: 4,
        value: "Working Professional",
      },
    ],
    breakpoint: 5,
    disabled: true,
    validation: { required: true },
  },
  {
    isTextInput: true,
    name: "tell_us_something_about_you_and_your_passion_towards_pet",
    label: "Tell us Something about you and your passion towards pet",
    placeholder: "Enter Name",
    breakpoint: 10,
    multiline: true,
    rows: 3,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isDropdown: true,
    name: "professional_status",
    labelText: "Professional Status",
    placeholder: "Select Profession",
    DropdownData: [
      {
        id: 1,
        value: "Student",
      },
      {
        id: 2,
        value: "Housewife",
      },
      {
        id: 3,
        value: "Professional boarder",
      },
      {
        id: 4,
        value: "Working Professional",
      },
    ],
    breakpoint: 6,
    disabled: true,
    validation: { required: true },
  },
  {
    isDropdown: true,
    name: "professional_status",
    labelText: "Professional Status",
    placeholder: "Select Profession",
    DropdownData: [
      {
        id: 1,
        value: "Student",
      },
      {
        id: 2,
        value: "Housewife",
      },
      {
        id: 3,
        value: "Professional boarder",
      },
      {
        id: 4,
        value: "Working Professional",
      },
    ],
    breakpoint: 6,
    disabled: true,
    validation: { required: true },
  },
  {
    isMultipleSelectChip: true,
    name: "list_the_pet_services_you_are_providing",
    breakpoint: 6,
    label: "List the Pet Services you are Providing",
    labelText: "Primary Skills",
    dropPlaceholder: "Primary Skills",
    disabled: true,
    DropdownData: [
      {
        id: 1,
        value: "Cartomancy",
      },
      {
        id: 2,
        value: "Face Reading",
      },
      {
        id: 3,
        value: "Lal Kitab",
      },
      {
        id: 4,
        value: "Life Coach",
      },
      {
        id: 5,
        value: "Loshu Grid",
      },
    ],
    validation: { required: true },
    error_message: "Primary Skills",
  },
  {
    isDropdown: true,
    name: "professional_status",
    labelText: "Professional Status",
    placeholder: "Select Profession",
    dropPlaceholder: "Primary Skills",
    DropdownData: [
      {
        id: 1,
        value: "Student",
      },
      {
        id: 2,
        value: "Housewife",
      },
      {
        id: 3,
        value: "Professional boarder",
      },
      {
        id: 4,
        value: "Working Professional",
      },
    ],
    breakpoint: 6,
    disabled: true,
    validation: { required: true },
  },
  {
    isCustomTypography: true,
    name: "header_menu",
    text: "Amenities",
    breakpoint: 12,
  },
  {
    isRadioAction: true,
    name: "can_provide_oral_medication",
    label: "Can provide oral medication?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "can_provide_oral_medication",
    label: "Can provide oral medication?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "can_provide_oral_medication",
    label: "Can provide oral medication?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "can_provide_oral_medication",
    label: "Can provide oral medication?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "can_provide_oral_medication",
    label: "Can provide oral medication?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "can_provide_oral_medication",
    label: "Can provide oral medication?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isCustomTypography: true,
    name: "header_menu",
    text: "Service Overview",
    breakpoint: 12,
  },
  {
    isTextInput: true,
    name: "service_overview",
    label: "Service Overview",
    placeholder: "",
    breakpoint: 12,
    multiline: true,
    rows: 3,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isRadioAction: true,
    name: "can_provide_oral_medication",
    label: "Can provide oral medication?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isTextInput: true,
    name: "location",
    label: "Enter Location",
    placeholder: "",
    breakpoint: 6,
    // multiline: true,
    // rows: 3,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isProfileImageUploader: true,
    name: "fileUploader",
    label: "Add Photos",
    breakpoint: 5,
    customClass: "profileImageContainer",
    validation: { required: true },
    error_message: "Upload Image",
  },
  {
    isEmptySpace: true,
    breakpoint: 6,
    name: "space",
  },
];
export const DefaultAboutPetValues = {
  professional_status: "",
  tell_us_something_about_you_and_your_passion_towards_pet: "",
  tell_us_about_the_type_of_pet_you_have_and_your_experience: "",
  tell_us_about_the_type_of_pet_you_have_and_your_experience_two: "",
  can_provide_oral_medication: "",
  can_you_provide_first_aid: "",
};
