export const ServiceDetailsEntries = [
  {
    isTextInput: true,
    name: "package_name",
    label: "Name of your Package",
    placeholder: "Enter Name",
    breakpoint: 12,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "included",
    label: "Whats Included?",
    placeholder: "List What are included with the package",
    breakpoint: 12,
    validation: { required: true },
    multiline: true,
    rows: 3,
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "rate",
    label: "Rate",
    placeholder: "Enter the rate of the package",
    breakpoint: 12,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
];
export const DefaultServiceDetailsValues = {
  package_name: "",
  included: "",
  rate: "",
};