export const tabArray = [
  {
    id: 1,
    tabText: "Pet Walking",
    tabColor: "#F85A47",
  },
  {
    id: 2,
    tabText: "Grooming",
    tabColor: "#F85A47",
  },
];
export const ServicePackageEntries = [
  {
    isTextInput: true,
    name: "AddOnPackage",
    label: "Name Of Your Add On Package",
    placeholder: "Enter Package Name",
    breakpoint: 11,
    value: "state",
    type: "text",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
  },

  {
    isSubmitButton: true,
    name: "add_button",
    buttonTitle: "+",
    breakpoint: 1,
    customClass: "sourceButton",
  },

  {
    isTextInput: true,
    name: "WhatisIncluded",
    label: "What is Included ?",
    placeholder: "List what are included with the package",
    breakpoint: 12,
    value: "state",
    type: "text",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
    multiline: true,
    rows: 2,
  },
  {
    isTextInput: true,
    name: "Rate",
    label: "Rate",
    placeholder: "Enter the rate of packages",
    breakpoint: 12,
    value: "state",
    type: "text",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
  },

  {
    isEmptySpace: true,
    breakpoint: 10,
    name: "space",
  },
];
export const GroomingEntries = [
  {
    isCustomTypography: true,
    name: "header_menu",
    text: "Fill up details about your service package for Pet Walking",
    breakpoint: 12,
  },
  {
    isTextInput: true,
    name: "firstText",
    label: "Name of your Pet Walking package",
    placeholder: "Enter Name",
    breakpoint: 10,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "whats_included",
    label: "Whats Included?",
    placeholder: "",
    breakpoint: 12,
    multiline: true,
    rows: 3,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "rate",
    label: "Rate",
    placeholder: "Enter Name",
    breakpoint: 12,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
];
export const DefaultServicePackageValues = {
  header_menu: "",
  firstText: "",
  whats_included: "",
  rate: "",
};
