export const ServiceDetailsEntries = [
  {
    isMultipleSelectChip: true,
    name: "list_the_pet_services_you_are_providing",
    breakpoint: 6,
    label: "List the Pet Services you are Providing",
    labelText: "Primary Skills",
    dropPlaceholder: "Primary Skills",
    disabled: true,
    DropdownData: [
      {
        id: 1,
        value: "Cartomancy",
      },
      {
        id: 2,
        value: "Face Reading",
      },
      {
        id: 3,
        value: "Lal Kitab",
      },
      {
        id: 4,
        value: "Life Coach",
      },
      {
        id: 5,
        value: "Loshu Grid",
      },
    ],
    validation: { required: true },
    error_message: "Primary Skills",
  },
  {
    isMultipleSelectChip: true,
    name: "category_of_pets_boarded",
    breakpoint: 6,
    label: "Category of Pets Boarded",
    labelText: "Primary Skills",
    dropPlaceholder: "",
    disabled: true,
    DropdownData: [
      {
        id: 1,
        value: "Cartomancy",
      },
      {
        id: 2,
        value: "Face Reading",
      },
      {
        id: 3,
        value: "Lal Kitab",
      },
      {
        id: 4,
        value: "Life Coach",
      },
      {
        id: 5,
        value: "Loshu Grid",
      },
      {
        id: 6,
        value: "Motivational Coach",
      },
    ],
    validation: { required: true },
    error_message: "Primary Skills",
  },
  {
    isTextInput: true,
    name: "no_of_pets",
    label: "No of Pets (Boarding Capacity)",
    placeholder: "Enter Name",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "providing_these_services_at",
    label: "Where are you providing these services at",
    placeholder: "Enter Name",
    breakpoint: 6,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isRadioAction: true,
    name: "do_you_provide_doorstep_service",
    label: "Do you provide doorstep services?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isTextInput: true,
    name: "service_overview",
    label: "Service Overview",
    placeholder: "",
    breakpoint: 12,
    multiline: true,
    rows: 3,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isRadioAction: true,
    name: "do_you_have_dedicated_boarding_area_for_pets",
    label: "Do you have dedicated boarding area for pets?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "do_you_have_kids_at_home",
    label: "Do you have kids at home?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "can_provide_oral_medication",
    label: "Can provide oral medication?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "do_you_have_a_playing_area_for_pets",
    label: "Do you have a playing area for pets?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "pets_allowed_on_beds",
    label: "Pets allowed on Beds?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "do_you_have_air_conditioner_in_pet_sleeping_area",
    label: "Do you have air conditioner in pet sleeping area?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "pets_allowed_on_furniture",
    label: "Pets allowed on Furniture?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "do_you_have_other_pets_at_home",
    label: "Do you have other pets at home?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "do_you_have_other_pets_at_home_two",
    label: "Do you have other pets at home?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "do_you_pet_sleeping_area",
    label: "Do you A/C in pet sleeping area?",
    breakpoint: 6,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    validation: { required: true },
    requiredField: true,
    error_message: "Status",
  },
];
export const DefaultServiceDetailsValues = {
  list_the_pet_services_you_are_providing: "",
  category_of_pets_boarded: "",
  no_of_pets: "",
  providing_these_services_at: "",
  do_you_provide_doorstep_service: "",
  service_overview: "",
  do_you_have_dedicated_boarding_area_for_pets: "",
  do_you_have_kids_at_home: "",
  can_provide_oral_medication: "",
  do_you_have_a_playing_area_for_pets: "",
  pets_allowed_on_beds: "",
  do_you_have_air_conditioner_in_pet_sleeping_area: "",
  pets_allowed_on_furniture: "",
  do_you_have_other_pets_at_home: "",
  do_you_have_other_pets_at_home_two: "",
  do_you_pet_sleeping_area:""
};