export const tabArray = [
  {
    id: 1,
    tabText: "Pet Walking",
    tabColor: "#F85A47",
  },
  {
    id: 2,
    tabText: "Grooming",
    tabColor: "#F85A47",
  },
];
export const ServicePackageEntries = [
  {
    isCustomTypography: true,
    name: "header_menu",
    text: "Fill up details about your service package for Pet Walking",
    breakpoint: 12,
  },
  {
    isTextInput: true,
    name: "firstText",
    label: "Name of your Pet Walking package",
    placeholder: "Enter Name",
    breakpoint: 10,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "whats_included",
    label: "Whats Included?",
    placeholder: "",
    breakpoint: 12,
    multiline: true,
    rows: 3,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "rate",
    label: "Rate",
    placeholder: "Enter Name",
    breakpoint: 12,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
];
export const GroomingEntries = [
  {
    isCustomTypography: true,
    name: "header_menu",
    text: "Fill up details about your service package for Pet Walking",
    breakpoint: 12,
  },
  {
    isTextInput: true,
    name: "firstText",
    label: "Name of your Pet Walking package",
    placeholder: "Enter Name",
    breakpoint: 10,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "whats_included",
    label: "Whats Included?",
    placeholder: "",
    breakpoint: 12,
    multiline: true,
    rows: 3,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
  {
    isTextInput: true,
    name: "rate",
    label: "Rate",
    placeholder: "Enter Name",
    breakpoint: 12,
    validation: { required: true },
    pattern: /^[a-zA-Z ]*$/,
    requiredField: true,
    customClass: "textBox",
    error_message: "First Text",
    validation_error_message: "Text is in Invalid format",
  },
];
export const DefaultServicePackageValues = {
  header_menu: "",
  firstText: "",
  whats_included: "",
  rate: "",
};
