export const PetHostAmentiesEntries = [
  {
    isRadioAction: true,
    name: "dedicatedboardingarea",
    label: "Do you have dedicated boarding area for pets?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "kidsathome",
    label: "Do you have kids at home?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Food",
    label: "Food",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "playingarea",
    label: "Do you have a playing area for pets?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Beds",
    label: "Pets allowed on Beds?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "CuddleTime",
    label: "Cuddle Time",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },

  {
    isRadioAction: true,
    name: "A/C",
    label: "Do you A/C in pet sleeping area?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Furniture",
    label: "Pets allowed on Furniture?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Walking",
    label: "Walking",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "other pets",
    label: "Do you have other pets at home?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Pets allowed",
    label: "Pets allowed on Beds?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Play time",
    label: "Play time",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },

  {
    isRadioAction: true,
    name: "dedicated boarding area",
    label: "Do you have dedicated boarding area for pets?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "kids at home",
    label: "Do you have kids at home?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Food",
    label: "Food",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "playing area",
    label: "Do you have a playing area for pets?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Beds",
    label: "Pets allowed on Beds?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Cuddle Time",
    label: "Cuddle Time",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },

  {
    isRadioAction: true,
    name: "AC",
    label: "Do you A/C in pet sleeping area?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Furniture",
    label: "Pets allowed on Furniture?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Walking",
    label: "Walking",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "otherpets",
    label: "Do you have other pets at home?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Petsallowed",
    label: "Pets allowed on Beds?",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isRadioAction: true,
    name: "Playtime",
    label: "Play time",
    breakpoint: 4,
    radioButtonData: [{ name: "Yes" }, { name: "No" }],
    defaultValue: "Yes",
    validation: { required: true },
    error_message: "Status",
  },
];

export const DefaultAmentiesEntriesValues = {
  dedicatedboardingarea: "",
  kidsathome: "",
  Food: "",
  playingarea: "",
  Beds: "",
  CuddleTime: "",
  AC: "",
  Furniture: "",
  Walking: "",
  otherpets: "",
  Petsallowed: "",
  Playtime: "",
  submit_button: "",
};
