export const PetHostBasicDetailsEntries = [
  {
    isEmptySpace: true,
    breakpoint: 5,
    name: "space",
  },

  {
    isTextInput: true,
    name: "Name of Pet",
    label: "Your Name",
    placeholder: "Enter Your Name",
    breakpoint: 6,
    type: "text",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
  },
  {
    isTextInput: true,
    name: "mobile_number",
    label: "Mobile Number",
    breakpoint: 6,
    type: "number",
    pattern: /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/,
    validation: { required: true },
    validation_error_message: "Mobile number must be 10 digits.",
    requiredField: true,
    error_message: "Mobile Number",
  },
  {
    isRadioAction: true,
    name: "Gender",
    label: "Gender",
    breakpoint: 6,
    radioButtonData: [{ name: "Male" }, { name: "Female" }, { name: "Others" }],
    defaultValue: "Male",
    validation: { required: true },
    error_message: "Status",
  },
  {
    isBirthdayPicker: true,
    name: "dob",
    date: true,
    label: "Date of Birth",
    placeholder: "DD-MM-YYYY",
    pattern: /^\d{2}-[a-zA-Z]{3}-\d{4}$/,
    breakpoint: 6,
    validation_error_message: "Date of Birth is in Invalid format",
    validation: { required: true },
    requiredField: true,
    maxDate: "11/02/2004",
    error_message: "Date of Birth",
  },
  {
    isTextInput: true,
    name: "Name Of Your Pet Boarding Space",
    label: "Name Of Your Pet Boarding Space",
    placeholder: "Enter Name Of Pet Boarding Space",
    breakpoint: 6,
    type: "text",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
  },
  {
    isTextInput: true,
    name: "Address",
    label: "Address",
    breakpoint: 6,
    type: "text",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
    multiline: true,
    rows: 2,
  },
  {
    isTextInput: true,
    name: "City",
    label: "City",
    placeholder: "Enter Your City",
    breakpoint: 6,
    type: "text",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
  },
  {
    isTextInput: true,
    name: "State",
    label: "State",
    placeholder: "Enter Your State",
    breakpoint: 6,
    type: "text",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
  },
  {
    isTextInput: true,
    name: "Locality",
    label: "Locality",
    placeholder: "Enter Your Locality",
    breakpoint: 6,
    type: "text",
    customClass: "",
    pattern: /^[a-zA-Z ]*$/,
    validation: { required: true },
    requiredField: true,
    validation_error_message: "Text is in Invalid format",
    error_message: "First Text",
  },
  {
    isTextInput: true,
    name: "Pincode",
    label: "Pincode",
    breakpoint: 6,
    type: "number",
    pattern: /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/,
    validation: { required: true },
    validation_error_message: "Mobile number must be 10 digits.",
    requiredField: true,
    error_message: "Mobile Number",
  },
  {
    isEmptySpace: true,
    breakpoint: 11,
    name: "space",
  },
  {
    isSubmitButton: true,
    name: "submit_button",
    buttonTitle: "Submit",
    breakpoint: 1,
    customClass: "sourceButton",
  },
];
